@startuml
'https://plantuml.com/class-diagram

class Etudiant{
- identité : Identite
- listNotes: HashMap<Matière:String,Note:int>
}

class HashMap<Matière:String,Coef:String>{}
class Formation{
-idfomation:String
- matières: HashMap
}
Formation -> HashMap

class TreeMap<Matière:String,idfomation:String>{}
class GroupeEtudiant{
- étudiants : collection
- groupe: formation?
}
class Identite{
-NIP: String
-nom: String
-prenom: String
}
GroupeEtudiant -> TreeMap
@enduml